### ISSUE TITLE
High Availability of AKO

### ISSUE THREAD

**Issue by christianang** [vmware-tanzu/load-balancer-operator-for-kubernetes#247]
**Describe the feature request**

AKODeploymentConfig doesn't allow a user to configure the replica count, which is useful for high availablity.

Proposal is to add `replicaCount` to `AKODeploymentConfig`'s `ExtraConfigs` struct, which will set the `loadBalancerAndIngressService.config.replica_count` field.

AKODeploymentConfig example:
```
apiVersion: networking.tkg.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
  name: my-ako-deployment-config
spec:
  ...
  extraConfigs:
    replicaCount: 2
  ...
```
which creates the following `load-balancer-and-ingress-service-data-values` secret:
```
loadBalancerAndIngressService:
    name: ako-tkg-system-tkg-mgmt-vc
    namespace: avi-system
    config:
        ...
        replica_count: 2
        ...
```

**Describe alternatives you've considered**

None

**Affected product area (please put an X in all that apply)**

- [X] Docs
- [X] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience

**Additional context**

Documentation about HA AKO: https://docs.vmware.com/en/VMware-NSX-Advanced-Load-Balancer/1.11/Avi-Kubernetes-Operator-Guide/GUID-90CFB939-8D47-44EF-856B-DDD9F2677B41.html?hWord=N4IghgNiBcIBYEsDmcAEYBuYETAIxwQBcBPEAXyA
